version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            APP_KEY: ${APP_KEY}
            DB_CONNECTION: pgsql
            DB_HOST: postgres
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_SSLMODE: prefer
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - postgres
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres:

